apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: tekton-cleanup
spec:
  params:
  - name: namespace
    description: Namespace to cleanup to in the target cluster
  - name: clusterResource
    description: Name of the cluster resource that points to the target cluster
  - name: keep
    description: Amount of old resources to keep
    default: "200"
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: TaskRun
    metadata:
      generateName: cleanup-$(tt.params.namespace)-taskrun-
    spec:
      serviceAccountName: pipeline
      taskSpec:
        params:
        - name: keep
        - name: namespace
        steps:
        - name: cleanup-pr-tr
          image: gcr.io/tekton-releases/dogfooding/tkn
          script: |
            #!/bin/sh
            set -ex
            # A safety check, to avoid deleting too much!
            if [[ $(params.keep) == "" ]]; then
              echo "Please specify a value for keep >= 0"
              exit 1
            fi
            # Cleanup pipelineruns first, as this will delete tasksruns too
            if [[ $(params.keep) -eq 0 ]]; then
              tkn pr delete -n $(params.namespace) --all
              tkn tr delete -n $(params.namespace) --all
              exit 0
            fi
            tkn pr delete -n $(params.namespace) --keep $(params.keep)
            # Keep double the amount of tr, for standalone trs
            tkn tr delete -n $(params.namespace) --keep $(( $(params.keep) * 2 ))
      params:
      - name: keep
        value: $(tt.params.keep)
      - name: namespace
        value: $(tt.params.namespace)
