apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: okd-coreos-prod
spec:
  serviceAccountName: pipeline
  triggers:
    - name: okd-coreos-prod-trigger
      bindings:
        - ref: okd-coreos-prod
      template:
        ref: okd-coreos-prod
