apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: scos-all
  namespace: okd-team
spec:
  params:
    - default: '4.12'
      name: version
      type: string
  tasks:
    - name: scos-cosa-copy
      params:
        - name: version
          value: $(params.version)
      taskRef:
        kind: Task
        name: scos-cosa-copy
      workspaces:
        - name: workdir
          workspace: shared-workspace
    - name: scos-cosa-init
      params:
        - name: version
          value: $(params.version)
      runAfter:
        - scos-cosa-copy
      taskRef:
        kind: Task
        name: scos-cosa-init
      workspaces:
        - name: srv
          workspace: shared-workspace
    - name: scos-cosa-build
      params:
        - name: version
          value: $(params.version)
      runAfter:
        - scos-cosa-init
      taskRef:
        kind: Task
        name: scos-cosa-build
      workspaces:
        - name: srv
          workspace: shared-workspace
    - name: scos-cosa-buildextend
      params:
        - name: version
          value: $(params.version)
      runAfter:
        - scos-cosa-build
      taskRef:
        kind: Task
        name: scos-cosa-buildextend
      workspaces:
        - name: srv
          workspace: shared-workspace
    - name: scos-cosa-test
      params:
        - name: version
          value: $(params.version)
      runAfter:
        - scos-cosa-buildextend
      taskRef:
        kind: Task
        name: scos-cosa-test
      workspaces:
        - name: srv
          workspace: shared-workspace
  workspaces:
    - name: shared-workspace
