apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cosa-build
spec:
  steps:
    - image: 'quay.io/coreos-assembler/coreos-assembler:latest'
      name: fetch-and-build
      resources:
        limits:
          devices.kubevirt.io/kvm: '1'
          memory: 4Gi
        requests:
          devices.kubevirt.io/kvm: '1'
          memory: 4Gi
      script: |
        #!/usr/bin/env bash
        set -euxo pipefail

        cd /workspace/coreos
        cosa fetch
        cosa build ostree
        cosa buildextend-extensions
        #cosa push-container --authfile=${REGISTRY_AUTHFILE} quay.io/okd/centos-stream-coreos-9:latest
  workspaces:
    - mountPath: /workspace
      name: ws
