apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cosa-init 
spec:
  params:
    - description: The manifest repo URL
      name: repo
      type: string
    - description: The manifest repo branch
      name: branch
      type: string
    - description: The CoreOS variant
      name: variant
      type: string
    - description: The OKD version
      name: version
      type: string
  steps:
    - image: 'quay.io/coreos-assembler/coreos-assembler:latest'
      name: prepare-repo
      resources:
        limits:
          devices.kubevirt.io/kvm: '1'
          memory: 4Gi
        requests:
          devices.kubevirt.io/kvm: '1'
          memory: 4Gi
      script: |
        #!/usr/bin/env bash 
        set -euxo pipefail 

        mkdir -p /srv/coreos
        cd /srv/coreos

        cat << INFO
        Initializing coreos-assembler:
        
        Manifest repo:  $(params.repo)
        Branch:         $(params.branch)

        OKD version:    $(params.version)
        CoreOS variant: $(params.variant)
        
        INFO

        cosa init \
            --branch $(params.branch) \
            --variant $(params.variant) \
            $(params.repo)

        # Update symlinks for default manifests
        cosa update-variant default $(params.variant)

        # Move rpms into scope of COSA VM
        if [ -d "/srv/rpms" ]; then
          mv /srv/rpms /srv/coreos/
          createrepo_c /srv/coreos/rpms
        fi

        # TODO: Upstream to openshift/os
        sed -i 's/rhel-9.*-server-ose.*/artifacts/' $(readlink -f src/config/manifest.yaml)

        # https://github.com/openshift/os/pull/1006
        sed -i 's|file:///usr/share/distribution-gpg-keys/centos|https://www.centos.org/keys|g' src/config/c9s.repo

        # tmp fix for replacing labels in manifest
        sed -i 's/"4.13"/"$(params.version}"/g' /srv/coreos/src/config/manifest-c9s.yaml 

        # Get oc and hypershift from the yum repo in the artifacts image
        cat <<EOF >> src/config/c9s.repo

        [artifacts]
        name=OKD RPM artifacts
        baseurl=file:///srv/coreos/rpms/
        repo_gpgcheck=0
        gpgcheck=0
        enabled=1

        EOF

  workspaces:
    - mountPath: /srv
      name: ws
