apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cosa-upload-extensions
spec:
  params:
    - name: target-registry
      default: "quay.io/okd"
      type: string
    - name: extensions-container-image-name
      default: "centos-stream-coreos-9-extensions"
      type: string
  steps:
    - image: 'quay.io/coreos-assembler/coreos-assembler:latest'
      name: upload-extensions-image
      script: |
        #!/usr/bin/env bash
        set -euxo pipefail

        cd /workspace/coreos
        cosa push-container --authfile=/registry-credentials/.dockerconfigjson --image=extensions-container $(params.target-registry)/$(params.extensions-container-image-name)

  workspaces:
    - mountPath: /registry-credentials
      name: regcred
    - mountPath: /workspace
      name: ws
