apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cosa-build
spec:
  steps:
    - image: 'quay.io/coreos-assembler/coreos-assembler:latest'
      name: fetch-and-build
      resources:
        limits:
          cpu: 1
          devices.kubevirt.io/kvm: '1'
          memory: 4Gi
        requests:
          cpu: 1
          devices.kubevirt.io/kvm: '1'
          memory: 4Gi
      script: |
        #!/usr/bin/env bash
        set -euxo pipefail

        cd /workspace/coreos
        cosa fetch
        cosa build ostree

        # The rpms that were extracted from the artifacts image
        # are not present inside the container used to build the
        # extensions, however `rpm-ostree compose extensions`
        # will try to fetch metadata for all repos listed in
        # both {manifest,extensions}.yaml 
        # TODO: Find a more elegant way to do this
        sed -i 's/- artifacts//' $(readlink -f src/config/manifest.yaml)

        sed -i 's|RUN rpm-ostree compose extensions --rootfs=/ --output-dir=/usr/share/rpm-ostree/extensions/ {manifest,extensions}.yaml|RUN ls -al \&\& cat c9s.repo \&\& rpm-ostree compose extensions --rootfs=/ --output-dir=/usr/share/rpm-ostree/extensions/ {manifest,extensions}.yaml|' src/config/extensions/Dockerfile

        cosa build-extensions-container

  workspaces:
    - mountPath: /workspace
      name: ws
