apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: scos-cosa-copy 
  namespace: okd-team
spec:
  params:
    - description: The version repo
      name: version
      type: string
  steps:
    - image: 'registry.ci.openshift.org/origin/4.12:artifacts'
      name: copy-okd-rpms
      resources: {}
      script: >
        #!/usr/bin/env bash  

        set -euxo pipefail 

        mkdir /workdir/okd-rpms 

        cp /srv/repo/openshift-{clients-0.0.1-*,hyperkube-*}.x86_64.rpm
        /workdir/okd-rpms 

        useradd builder 

        chown -R builder:builder /workdir/okd-rpms
  workspaces:
    - mountPath: /workdir
      name: workdir
