apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: scos-cosa-init 
  namespace: okd-team
spec:
  params:
    - description: The version repo
      name: version
      type: string
  steps:
    - image: 'quay.io/coreos-assembler/coreos-assembler:latest'
      name: assemble
      resources:
        limits:
          devices.kubevirt.io/kvm: '1'
          memory: 1Gi
        requests:
          devices.kubevirt.io/kvm: '1'
          memory: 1Gi
      script: >
        #!/usr/bin/env bash 

        set -euxo pipefail 

        echo $(params.version) 

        mkdir scos

        cd scos 

        cosa init https://github.com/openshift/os.git 

        ls -la /srv/okd-rpms

        mv /srv/okd-rpms /srv/scos/ 

        createrepo_c /srv/scos/okd-rpms 

        ln -snf "manifest-c9s.yaml" "src/config/manifest.yaml"  

        ln -snf "extensions-c9s.yaml" "src/config/extensions.yaml"  

        ln -snf "image-c9s.yaml" "src/config/image.yaml" 

        cp "src/config/repos/c9s.repo" "src/config/c9s.repo" 

        echo -e "\n[okd-rpms]\nname=OKD
        RPMs\nbaseurl=file:///srv/scos/okd-rpms/\nrepo_gpgcheck=0\ngpgcheck=0\nenabled=1\nmetadata_expire=-1"
        >> "src/config/c9s.repo" 

        echo -e "\n[okd-copr]\nname=OKD
        COPR\nbaseurl=https://download.copr.fedorainfracloud.org/results/@OKD/okd/centos-stream-9-\$basearch/\ntype=rpm-md\ngpgcheck=1\ngpgkey=https://download.copr.fedorainfracloud.org/results/@OKD/okd/pubkey.gpg\nrepo_gpgcheck=0\nenabled=1\n" 
        >> "src/config/c9s.repo" 

        sed -i 's/rhel-9-server-ose/okd-rpms\n  - okd-copr/' 
        "src/config/manifest.yaml"
  workspaces:
    - mountPath: /srv
      name: srv
