kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: okd-coreos-pipeline-view
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: okd-coreos-pipeline-view
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
