apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pipeline-scos-stable-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 40Gi
  storageClassName: local
