apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cosa-build-baseos
spec:
  params:
    - name: bucket-name
      default: ""
      type: string
    - name: endpoint-url
      default: ""
      type: string
    - name: aws-config-file
      default: "credentials"
      type: string
  steps:
    - image: 'quay.io/coreos-assembler/coreos-assembler:latest'
      name: fetch-and-build-baseos
      resources:
        limits:
          cpu: 1000m
          devices.kubevirt.io/kvm: '1'
          memory: 4Gi
        requests:
          cpu: 1000m
          devices.kubevirt.io/kvm: '1'
          memory: 4Gi
      script: |
        #!/usr/bin/env bash
        set -euxo pipefail

        cd /srv/coreos

        if [[ -z "$(params.endpoint-url)" || ! -f "$(workspaces.s3creds.path)/$(params.aws-config-file)" || -z "$(params.bucket-name)" ]]; then
          echo "Skipping buildfetch from S3 - bucket params not set"
        else
          cosa buildfetch \
          --url=s3://builds \
          --aws-config-file=$(workspaces.s3creds.path)/$(params.aws-config-file)
        fi
        cosa fetch
        cosa build ostree

  workspaces:
    - mountPath: /srv
      name: ws
    - name: s3creds
