apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../../manifests/tekton/tasks/base
  - ../../../manifests/tekton/pipelines/base
  # locally, we include kvm-device-plugin
  - ../../../manifests/tekton/daemonsets/base
resources:
  - namespace/namespace.yaml
namespace: okd-coreos-pipeline

