apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: okd-coreos-all-4.14-pipelinerun-
  annotations:
    operator.tekton.dev/prune.skip: "false"
    operator.tekton.dev/prune.resources: "taskrun, pipelinerun"
    operator.tekton.dev/prune.keep: "1"
    operator.tekton.dev/prune.strategy: "keep"
spec:
  params:
    - name: repo
      value: "https://github.com/openshift/os.git"
    - name: branch
      value: "master"
    - name: variant
      value: "scos"     
    - name: version
      value: "4.14"
    - name: release-stream
      value: "next"
    - name: rpm-artifacts-image
      value: "registry.ci.openshift.org/origin/4.14:artifacts"
    - name: target-registry
      value: "quay.io/okd"
    - name: baseos-container-image-name
      value: "centos-stream-coreos-9"
    - name: extensions-container-image-name
      value: "centos-stream-coreos-9-extensions"
    - name: s3-bucket-name
      value: "okd-scos"
    - name: s3-endpoint-url
      value: "https://okd-scos.s3.amazonaws.com/"
    - name: matrix-room
      value: "!nStsazaBvZCZQHPWTY:fedoraproject.org"
    - name: matrix-endpoint
      value: "matrix.org"
    - name: upload-container-images
      value: "true"
    - name: tag-latest
      value: "false"
    - name: upload-bootimages
      value: "true"
    - name: notify-matrix
      value: "true"
  pipelineRef:
    name: okd-coreos-all
  timeouts:
    pipeline: "4h0m0s"
  workspaces:
    - name: registry-credentials
      secret:
        secretName: okd-scos-robot-pull-secret
    - name: s3-credentials
      secret:
        secretName: okd-scos-aws-config
    - name: shared-workspace
      volumeClaimTemplate:
        spec:
          storageClassName: ocs-external-storagecluster-ceph-rbd
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 40Gi
